import "@/styles/main.scss";

import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

const rubik = Rubik({
    weight: ["400", "500"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Bookmark",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <Header />

                {children}

                <Footer />
            </body>
        </html>
    );
}
